### ISSUE TITLE
Use composer autoloading

### ISSUE THREAD

**Issue by marcovtwout** [mikehaertl/pdfable#14]
Could you do a new release, so the Composer autoloading is included?

**Comment by mikehaertl** [comment]
Hmm. This package would need a rewrite anyway. I've completely refactored [phpwkhtmltopdf](https://github.com/mikehaertl/phpwkhtmltopdf) now, so it should better be included as composer dependency instead. Unfortunately I won't find much time to do that anytime soon.

**Comment by marcovtwout** [comment]
In that case, could you make a small incremental release based on current master? If you could also include the open PR, that would be great.

**Comment by mikehaertl** [comment]
Done.

**Comment by marcovtwout** [comment]
Thanks!
