### ISSUE TITLE
Printing a table with results longer than one page

### ISSUE THREAD

**Issue by nashfx** [mikehaertl/pdfable#18]
Hi,

I'm printing a table with results from a search and the PDF its showing very bad.

I dont know why its showing this way and why is repeating the table head on the second page of results

![issue](https://cloud.githubusercontent.com/assets/7783609/11877522/07a2fcec-a4c2-11e5-80a2-5b06cfaa09bd.png)

**Comment by mikehaertl** [comment]
We can't do much about it here. You need to reorganize your page content and make it fit to a page. 

I've not tried it, but you may also have success with CSS `page-break-after` property: http://www.w3schools.com/cssref/pr_print_pageba.asp
