### ISSUE TITLE
YYI install pdftble on behaviors

### ISSUE THREAD

**Issue by antoniosap** [mikehaertl/pdfable#20]
Hi all,    

on advanced model on yyi 2 pdfable give me error: ext.pdfable.Pdfable non found.
any ideas? i follow many tutorial for yyi 1. no results.

`
public function behaviors()  {

        return [

            'access' => [

                'class' => AccessControl::className(),

                'only' => ['logout', 'signup'],

                'rules' => [

                    [

                        'actions' => ['signup'],

                        'allow' => true,

                        'roles' => ['?'],

                    ],
                    [

                        'actions' => ['logout'],

                        'allow' => true,

                        'roles' => ['@'],

                    ],

                ],

            ],

            'verbs' => [

                'class' => VerbFilter::className(),

                'actions' => [

                    'logout' => ['post'],

                ],

            ],
        	//'pdfable' => [

        	//	'class' => 'ext.pdfable.Pdfable',

        	//],

        ];

    }
`

**Comment by mikehaertl** [comment]
This extension is not compatible with Yii2.
