### ISSUE TITLE
Improve default temp directory

### ISSUE THREAD

**Issue by marcovtwout** [mikehaertl/pdfable#21]
Pdfable uses the default tmpAlias of 'application.runtime'. Since the runtime path is already defined in CWebApplication, I think it would be better to use this default: `Yii::app()->getRuntimePath()`

I didn't even notice the default path was incorrect until upgrading to PHP 7.1, which throws a notice when you try to generate a tmpname() file within the wrong directory.

**Comment by mikehaertl** [comment]
@marcovtwout As you may have noticed this extension is not much maintained anymore lately. But feel free to submit a PR for this change and I'll merge.

**Comment by mikehaertl** [comment]
Just release 1.0.4 with your change included. Thanks!

**Comment by marcovtwout** [comment]
No problem, thanks for the quick response on your part. :)
