### ISSUE TITLE
Could not run command '/usr/bin/wkhtmltopdf' --no-outline --encoding

### ISSUE THREAD

**Issue by closerwalk** [mikehaertl/pdfable#8]
07:29:01.177191 error   ext.pdfable.Pdfable 
Could not create PDF for view invoice
in /var/www/inspections/protected/extensions/pdfable/Pdfable.php (209)
in
/var/www/inspections/protected/extensions/pdfable/pdfable/controllers/DemoController.php
(53)
in
/var/www/inspections/protected/extensions/pdfable/pdfable/controllers/DemoController.php
(53)
07:29:01.177294 trace   ext.pdfable.Pdfable 
Could not run command '/usr/bin/wkhtmltopdf' --no-outline --encoding
'UTF-8' --margin-top '0' --margin-right '0' --margin-bottom '0'
--margin-left '0'
/var/www/inspections/protected/runtime/tmp_WkHtmlToPdf_cesvmI.html
--user-style-sheet
'/var/www/inspections/protected/extensions/pdfable/pdfable/assets/css/pdf.css'
/var/www/inspections/protected/runtime/tmp_WkHtmlToPdf_dJXTD5:
Unknown long argument --no-outline

Name:
  wkhtmltopdf 0.9.9

Synopsis:
  wkhtmltopdf [OPTIONS]... <input file> [More input files] <output file>

Description:
  Converts one or more HTML pages into a PDF document, _not_ using
wkhtmltopdf
  patched qt.

General Options:
      --collate                       Collate when printing multiple copies
      --copies <number>               Number of copies to print into the
pdf                                      file (default 1)
      --extended-help                 Display more extensive help,
detailing                                      less common command switches
  -h, --help                          Display help
  -O, --orientation <orientation>     Set orientation to Landscape or
Portrait
  -s, --page-size <size>              Set paper size to: A4, Letter, etc.
      --password <password>           HTTP Authentication password
  -p, --proxy <proxy>                 Use a proxy
  -q, --quiet                         Be less verbose
      --username <username>           HTTP Authentication username
  -V, --version                       Output version information an exit
Reduced Functionality:
  This version of wkhtmltopdf has been compiled against a version of QT
without
  the wkhtmltopdf patches. Therefore some features are missing, if you need
  these features please use the static version.

  Currently the list of features only supported with patch QT includes:
- Printing more then one HTML document into a PDF file.
- Running without an X11 server.
- Adding a document outline to the PDF file.
- Adding headers and footers to the PDF file.
- Generating a table of contents.
- Adding links in the generated PDF file.
- Printing using the screen media-type.
- Disabling the smart shrink feature of webkit.

Contact:
  If you experience bugs or want to request new features please visit 
  http://code.google.com/p/wkhtmltopdf/issues/list, if you have any
problems
  or comments please feel free to contact me: see 
  http://www.madalgo.au.dk/~jakobt/#about

in /var/www/inspections/protected/extensions/pdfable/Pdfable.php (210)
in
/var/www/inspections/protected/extensions/pdfable/pdfable/controllers/DemoController.php
(53)
in
/var/www/inspections/protected/extensions/pdfable/pdfable/controllers/DemoController.php
(53)

My system is Ubuntu 12.04.1 LTS

I have installed wkhtmltopdf per this and in the command line it works brilliantly

apt-get install wkhtmltopdf
apt-get install xvfb
echo 'xvfb-run --server-args="-screen 0, 1024x768x24" /usr/bin/wkhtmltopdf $*' > /usr/bin/wkhtmltopdf.sh
chmod a+x /usr/bin/wkhtmltopdf.sh
ln -s /usr/bin/wkhtmltopdf.sh /usr/local/bin/wkhtmltopdf
wkhtmltopdf http://www.google.com output.pdf

**Comment by nhantam** [comment]
11 Aug 2023: My Error 
Could not run command /usr/local/bin/wkhtmltoimage '--encoding' 'UTF-8' '--quality' '100' '--user-style-sheet'
